name: Hello CI

on: [push, pull_request]

jobs:
  test:
        runs-on: ubuntu-24.04
        steps:
              - name: hello
              - run: echo "Hello CI/CD"

              - name: Affiche la branche et l'auteur
              - run: |
                   echo "Branche actuelle : ${{ github.ref_name }}"
                   echo "Auteur du commit : ${{ github.actor }}"
